cpu_count: 4
packages:
  antspy: antspyx
  astropy: astropy
  attrs: attrs
  bids: pybids
  blosc2: blosc2
  cryptography: cryptography
  cuda: cuda-python
  cython: Cython
  dcmstack: dcmstack
  dirsync: dirsync
  einops: einops
  gdown: gdown
  gitpython: GitPython
  gputil: GPUtil
  h5py: h5py
  keras: keras==2.8.0
  list_imports: list-imports
  lmdb: lmdb
  lmfit: lmfit
  matplotlib: matplotlib==3.7.4
  mlflow: mlflow
  mss: mss
  nibabel: nibabel
  nilearn: nilearn
  nipy: nipy
  nipype: nipype
  nitime: nitime
  niworkflows: niworkflows
  nose: nose
  numba: numba
  numpy: numpy
  openCV: opencv-python
  pandas: pandas
  prompt_toolkit: prompt_toolkit
  psutil: psutil
  pynrrd: pynrrd
  pyqt6: PyQt6
  pyqt6-sip: PyQt6-sip
  pytest: pytest
  pytorch-ignite: pytorch-ignite
  pyvista: pyvista
  pyvistaqt: pyvistaqt
  ray: ray
  read_roi: read_roi
  scikit-image: scikit-image
  scikit-learn: scikit-learn
  scipy: scipy
  simpleITK: simpleITK
  sip: sip
  sympy: sympy
  tensorflow: tensorflow==2.19.0
  tkinter: tk
  torchvision: torchvision
  traits: traits
  transformers: transformers
  vedo: vedo
version: 25.10.06b
